In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\aditi\anaconda3\lib\site-packages (1.2.4)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pytz>=2017.3 in c:\users\aditi\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\aditi\anaconda3\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\aditi\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\aditi\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [3]:
import pandas as pd

In [4]:
pd.__version__

'1.2.4'

In [5]:
df = pd.read_csv(r'C:\Users\Aditi\AppData\Roaming\Microsoft\Windows\Network Shortcuts\pokemon_data.csv')

In [6]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [7]:
print(df.head(6))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60
5  5             Charmeleon   Fire     NaN  58      64       58       80

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False
5       65     80           1      False

In [8]:
#Read headings of columns 
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [9]:
#Reading contents of every column
print (df[['Name' , 'Type 1' , 'Attack']])

                      Name   Type 1  Attack
0                Bulbasaur    Grass      49
1                  Ivysaur    Grass      62
2                 Venusaur    Grass      82
3    VenusaurMega Venusaur    Grass     100
4               Charmander     Fire      52
..                     ...      ...     ...
795                Diancie     Rock     100
796    DiancieMega Diancie     Rock     160
797    HoopaHoopa Confined  Psychic     110
798     HoopaHoopa Unbound  Psychic     160
799              Volcanion     Fire     110

[800 rows x 3 columns]

In [10]:
#Getting only a few rows of particular column
print(df['Name'][0:6])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
5               Charmeleon
Name: Name, dtype: object

In [12]:
#Printing a row
print(df.iloc[1])

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [107]:
#Printing out a row
print(df.iloc[1:4])

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False

In [108]:
#Read a specific location (R,C)
print(df.iloc[2,1])

Venusaur

In [109]:
for index, row in df.iterrows():
    print (index, row[['Name','Type 1']])

0 Name      Bulbasaur
Type 1        Grass
Name: 0, dtype: object
1 Name      Ivysaur
Type 1      Grass
Name: 1, dtype: object
2 Name      Venusaur
Type 1       Grass
Name: 2, dtype: object
3 Name      VenusaurMega Venusaur
Type 1                    Grass
Name: 3, dtype: object
4 Name      Charmander
Type 1          Fire
Name: 4, dtype: object
5 Name      Charmeleon
Type 1          Fire
Name: 5, dtype: object
6 Name      Charizard
Type 1         Fire
Name: 6, dtype: object
7 Name      CharizardMega Charizard X
Type 1                         Fire
Name: 7, dtype: object
8 Name      CharizardMega Charizard Y
Type 1                         Fire
Name: 8, dtype: object
9 Name      Squirtle
Type 1       Water
Name: 9, dtype: object
10 Name      Wartortle
Type 1        Water
Name: 10, dtype: object
11 Name      Blastoise
Type 1        Water
Name: 11, dtype: object
12 Name      BlastoiseMega Blastoise
Type 1                      Water
Name: 12, dtype: object
13 Name      Caterpie
Type 1         Bug
Name: 13, dtype: object
14 Name      Metapod
Type 1        Bug
Name: 14, dtype: object
15 Name      Butterfree
Type 1           Bug
Name: 15, dtype: object
16 Name      Weedle
Type 1       Bug
Name: 16, dtype: object
17 Name      Kakuna
Type 1       Bug
Name: 17, dtype: object
18 Name      Beedrill
Type 1         Bug
Name: 18, dtype: object
19 Name      BeedrillMega Beedrill
Type 1                      Bug
Name: 19, dtype: object
20 Name      Pidgey
Type 1    Normal
Name: 20, dtype: object
21 Name      Pidgeotto
Type 1       Normal
Name: 21, dtype: object
22 Name      Pidgeot
Type 1     Normal
Name: 22, dtype: object
23 Name      PidgeotMega Pidgeot
Type 1                 Normal
Name: 23, dtype: object
24 Name      Rattata
Type 1     Normal
Name: 24, dtype: object
25 Name      Raticate
Type 1      Normal
Name: 25, dtype: object
26 Name      Spearow
Type 1     Normal
Name: 26, dtype: object
27 Name      Fearow
Type 1    Normal
Name: 27, dtype: object
28 Name       Ekans
Type 1    Poison
Name: 28, dtype: object
29 Name       Arbok
Type 1    Poison
Name: 29, dtype: object
30 Name       Pikachu
Type 1    Electric
Name: 30, dtype: object
31 Name        Raichu
Type 1    Electric
Name: 31, dtype: object
32 Name      Sandshrew
Type 1       Ground
Name: 32, dtype: object
33 Name      Sandslash
Type 1       Ground
Name: 33, dtype: object
34 Name      Nidoran (Female)
Type 1              Poison
Name: 34, dtype: object
35 Name      Nidorina
Type 1      Poison
Name: 35, dtype: object
36 Name      Nidoqueen
Type 1       Poison
Name: 36, dtype: object
37 Name      Nidoran (Male)
Type 1            Poison
Name: 37, dtype: object
38 Name      Nidorino
Type 1      Poison
Name: 38, dtype: object
39 Name      Nidoking
Type 1      Poison
Name: 39, dtype: object
40 Name      Clefairy
Type 1       Fairy
Name: 40, dtype: object
41 Name      Clefable
Type 1       Fairy
Name: 41, dtype: object
42 Name      Vulpix
Type 1      Fire
Name: 42, dtype: object
43 Name      Ninetales
Type 1         Fire
Name: 43, dtype: object
44 Name      Jigglypuff
Type 1        Normal
Name: 44, dtype: object
45 Name      Wigglytuff
Type 1        Normal
Name: 45, dtype: object
46 Name       Zubat
Type 1    Poison
Name: 46, dtype: object
47 Name      Golbat
Type 1    Poison
Name: 47, dtype: object
48 Name      Oddish
Type 1     Grass
Name: 48, dtype: object
49 Name      Gloom
Type 1    Grass
Name: 49, dtype: object
50 Name      Vileplume
Type 1        Grass
Name: 50, dtype: object
51 Name      Paras
Type 1      Bug
Name: 51, dtype: object
52 Name      Parasect
Type 1         Bug
Name: 52, dtype: object
53 Name      Venonat
Type 1        Bug
Name: 53, dtype: object
54 Name      Venomoth
Type 1         Bug
Name: 54, dtype: object
55 Name      Diglett
Type 1     Ground
Name: 55, dtype: object
56 Name      Dugtrio
Type 1     Ground
Name: 56, dtype: object
57 Name      Meowth
Type 1    Normal
Name: 57, dtype: object
58 Name      Persian
Type 1     Normal
Name: 58, dtype: object
59 Name      Psyduck
Type 1      Water
Name: 59, dtype: object
60 Name      Golduck
Type 1      Water
Name: 60, dtype: object
61 Name        Mankey
Type 1    Fighting
Name: 61, dtype: object
62 Name      Primeape
Type 1    Fighting
Name: 62, dtype: object
63 Name      Growlithe
Type 1         Fire
Name: 63, dtype: object
64 Name      Arcanine
Type 1        Fire
Name: 64, dtype: object
65 Name      Poliwag
Type 1      Water
Name: 65, dtype: object
66 Name      Poliwhirl
Type 1        Water
Name: 66, dtype: object
67 Name      Poliwrath
Type 1        Water
Name: 67, dtype: object
68 Name         Abra
Type 1    Psychic
Name: 68, dtype: object
69 Name      Kadabra
Type 1    Psychic
Name: 69, dtype: object
70 Name      Alakazam
Type 1     Psychic
Name: 70, dtype: object
71 Name      AlakazamMega Alakazam
Type 1                  Psychic
Name: 71, dtype: object
72 Name        Machop
Type 1    Fighting
Name: 72, dtype: object
73 Name       Machoke
Type 1    Fighting
Name: 73, dtype: object
74 Name       Machamp
Type 1    Fighting
Name: 74, dtype: object
75 Name      Bellsprout
Type 1         Grass
Name: 75, dtype: object
76 Name      Weepinbell
Type 1         Grass
Name: 76, dtype: object
77 Name      Victreebel
Type 1         Grass
Name: 77, dtype: object
78 Name      Tentacool
Type 1        Water
Name: 78, dtype: object
79 Name      Tentacruel
Type 1         Water
Name: 79, dtype: object
80 Name      Geodude
Type 1       Rock
Name: 80, dtype: object
81 Name      Graveler
Type 1        Rock
Name: 81, dtype: object
82 Name      Golem
Type 1     Rock
Name: 82, dtype: object
83 Name      Ponyta
Type 1      Fire
Name: 83, dtype: object
84 Name      Rapidash
Type 1        Fire
Name: 84, dtype: object
85 Name      Slowpoke
Type 1       Water
Name: 85, dtype: object
86 Name      Slowbro
Type 1      Water
Name: 86, dtype: object
87 Name      SlowbroMega Slowbro
Type 1                  Water
Name: 87, dtype: object
88 Name      Magnemite
Type 1     Electric
Name: 88, dtype: object
89 Name      Magneton
Type 1    Electric
Name: 89, dtype: object
90 Name      Farfetch'd
Type 1        Normal
Name: 90, dtype: object
91 Name       Doduo
Type 1    Normal
Name: 91, dtype: object
92 Name      Dodrio
Type 1    Normal
Name: 92, dtype: object
93 Name       Seel
Type 1    Water
Name: 93, dtype: object
94 Name      Dewgong
Type 1      Water
Name: 94, dtype: object
95 Name      Grimer
Type 1    Poison
Name: 95, dtype: object
96 Name         Muk
Type 1    Poison
Name: 96, dtype: object
97 Name      Shellder
Type 1       Water
Name: 97, dtype: object
98 Name      Cloyster
Type 1       Water
Name: 98, dtype: object
99 Name      Gastly
Type 1     Ghost
Name: 99, dtype: object
100 Name      Haunter
Type 1      Ghost
Name: 100, dtype: object
101 Name      Gengar
Type 1     Ghost
Name: 101, dtype: object
102 Name      GengarMega Gengar
Type 1                Ghost
Name: 102, dtype: object
103 Name      Onix
Type 1    Rock
Name: 103, dtype: object
104 Name      Drowzee
Type 1    Psychic
Name: 104, dtype: object
105 Name        Hypno
Type 1    Psychic
Name: 105, dtype: object
106 Name      Krabby
Type 1     Water
Name: 106, dtype: object
107 Name      Kingler
Type 1      Water
Name: 107, dtype: object
108 Name       Voltorb
Type 1    Electric
Name: 108, dtype: object
109 Name      Electrode
Type 1     Electric
Name: 109, dtype: object
110 Name      Exeggcute
Type 1        Grass
Name: 110, dtype: object
111 Name      Exeggutor
Type 1        Grass
Name: 111, dtype: object
112 Name      Cubone
Type 1    Ground
Name: 112, dtype: object
113 Name      Marowak
Type 1     Ground
Name: 113, dtype: object
114 Name      Hitmonlee
Type 1     Fighting
Name: 114, dtype: object
115 Name      Hitmonchan
Type 1      Fighting
Name: 115, dtype: object
116 Name      Lickitung
Type 1       Normal
Name: 116, dtype: object
117 Name      Koffing
Type 1     Poison
Name: 117, dtype: object
118 Name      Weezing
Type 1     Poison
Name: 118, dtype: object
119 Name      Rhyhorn
Type 1     Ground
Name: 119, dtype: object
120 Name      Rhydon
Type 1    Ground
Name: 120, dtype: object
121 Name      Chansey
Type 1     Normal
Name: 121, dtype: object
122 Name      Tangela
Type 1      Grass
Name: 122, dtype: object
123 Name      Kangaskhan
Type 1        Normal
Name: 123, dtype: object
124 Name      KangaskhanMega Kangaskhan
Type 1                       Normal
Name: 124, dtype: object
125 Name      Horsea
Type 1     Water
Name: 125, dtype: object
126 Name      Seadra
Type 1     Water
Name: 126, dtype: object
127 Name      Goldeen
Type 1      Water
Name: 127, dtype: object
128 Name      Seaking
Type 1      Water
Name: 128, dtype: object
129 Name      Staryu
Type 1     Water
Name: 129, dtype: object
130 Name      Starmie
Type 1      Water
Name: 130, dtype: object
131 Name      Mr. Mime
Type 1     Psychic
Name: 131, dtype: object
132 Name      Scyther
Type 1        Bug
Name: 132, dtype: object
133 Name      Jynx
Type 1     Ice
Name: 133, dtype: object

134 Name      Electabuzz
Type 1      Electric
Name: 134, dtype: object
135 Name      Magmar
Type 1      Fire
Name: 135, dtype: object
136 Name      Pinsir
Type 1       Bug
Name: 136, dtype: object
137 Name      PinsirMega Pinsir
Type 1                  Bug
Name: 137, dtype: object
138 Name      Tauros
Type 1    Normal
Name: 138, dtype: object
139 Name      Magikarp
Type 1       Water
Name: 139, dtype: object
140 Name      Gyarados
Type 1       Water
Name: 140, dtype: object
141 Name      GyaradosMega Gyarados
Type 1                    Water
Name: 141, dtype: object
142 Name      Lapras
Type 1     Water
Name: 142, dtype: object
143 Name       Ditto
Type 1    Normal
Name: 143, dtype: object
144 Name       Eevee
Type 1    Normal
Name: 144, dtype: object
145 Name      Vaporeon
Type 1       Water
Name: 145, dtype: object
146 Name       Jolteon
Type 1    Electric
Name: 146, dtype: object
147 Name      Flareon
Type 1       Fire
Name: 147, dtype: object
148 Name      Porygon
Type 1     Normal
Name: 148, dtype: object
149 Name      Omanyte
Type 1       Rock
Name: 149, dtype: object
150 Name      Omastar
Type 1       Rock
Name: 150, dtype: object
151 Name      Kabuto
Type 1      Rock
Name: 151, dtype: object
152 Name      Kabutops
Type 1        Rock
Name: 152, dtype: object
153 Name      Aerodactyl
Type 1          Rock
Name: 153, dtype: object
154 Name      AerodactylMega Aerodactyl
Type 1                         Rock
Name: 154, dtype: object
155 Name      Snorlax
Type 1     Normal
Name: 155, dtype: object
156 Name      Articuno
Type 1         Ice
Name: 156, dtype: object
157 Name        Zapdos
Type 1    Electric
Name: 157, dtype: object
158 Name      Moltres
Type 1       Fire
Name: 158, dtype: object
159 Name      Dratini
Type 1     Dragon
Name: 159, dtype: object
160 Name      Dragonair
Type 1       Dragon
Name: 160, dtype: object
161 Name      Dragonite
Type 1       Dragon
Name: 161, dtype: object
162 Name       Mewtwo
Type 1    Psychic
Name: 162, dtype: object
163 Name      MewtwoMega Mewtwo X
Type 1                Psychic
Name: 163, dtype: object
164 Name      MewtwoMega Mewtwo Y
Type 1                Psychic
Name: 164, dtype: object
165 Name          Mew
Type 1    Psychic
Name: 165, dtype: object
166 Name      Chikorita
Type 1        Grass
Name: 166, dtype: object
167 Name      Bayleef
Type 1      Grass
Name: 167, dtype: object
168 Name      Meganium
Type 1       Grass
Name: 168, dtype: object
169 Name      Cyndaquil
Type 1         Fire
Name: 169, dtype: object
170 Name      Quilava
Type 1       Fire
Name: 170, dtype: object
171 Name      Typhlosion
Type 1          Fire
Name: 171, dtype: object
172 Name      Totodile
Type 1       Water
Name: 172, dtype: object
173 Name      Croconaw
Type 1       Water
Name: 173, dtype: object
174 Name      Feraligatr
Type 1         Water
Name: 174, dtype: object
175 Name      Sentret
Type 1     Normal
Name: 175, dtype: object
176 Name      Furret
Type 1    Normal
Name: 176, dtype: object
177 Name      Hoothoot
Type 1      Normal
Name: 177, dtype: object
178 Name      Noctowl
Type 1     Normal
Name: 178, dtype: object
179 Name      Ledyba
Type 1       Bug
Name: 179, dtype: object
180 Name      Ledian
Type 1       Bug
Name: 180, dtype: object
181 Name      Spinarak
Type 1         Bug
Name: 181, dtype: object
182 Name      Ariados
Type 1        Bug
Name: 182, dtype: object
183 Name      Crobat
Type 1    Poison
Name: 183, dtype: object
184 Name      Chinchou
Type 1       Water
Name: 184, dtype: object
185 Name      Lanturn
Type 1      Water
Name: 185, dtype: object
186 Name         Pichu
Type 1    Electric
Name: 186, dtype: object
187 Name      Cleffa
Type 1     Fairy
Name: 187, dtype: object
188 Name      Igglybuff
Type 1       Normal
Name: 188, dtype: object
189 Name      Togepi
Type 1     Fairy
Name: 189, dtype: object
190 Name      Togetic
Type 1      Fairy
Name: 190, dtype: object
191 Name         Natu
Type 1    Psychic
Name: 191, dtype: object
192 Name         Xatu
Type 1    Psychic
Name: 192, dtype: object
193 Name        Mareep
Type 1    Electric
Name: 193, dtype: object
194 Name       Flaaffy
Type 1    Electric
Name: 194, dtype: object
195 Name      Ampharos
Type 1    Electric
Name: 195, dtype: object
196 Name      AmpharosMega Ampharos
Type 1                 Electric
Name: 196, dtype: object
197 Name      Bellossom
Type 1        Grass
Name: 197, dtype: object
198 Name      Marill
Type 1     Water
Name: 198, dtype: object
199 Name      Azumarill
Type 1        Water
Name: 199, dtype: object
200 Name      Sudowoodo
Type 1         Rock
Name: 200, dtype: object
201 Name      Politoed
Type 1       Water
Name: 201, dtype: object
202 Name      Hoppip
Type 1     Grass
Name: 202, dtype: object
203 Name      Skiploom
Type 1       Grass
Name: 203, dtype: object
204 Name      Jumpluff
Type 1       Grass
Name: 204, dtype: object
205 Name       Aipom
Type 1    Normal
Name: 205, dtype: object
206 Name      Sunkern
Type 1      Grass
Name: 206, dtype: object
207 Name      Sunflora
Type 1       Grass
Name: 207, dtype: object
208 Name      Yanma
Type 1      Bug
Name: 208, dtype: object
209 Name      Wooper
Type 1     Water
Name: 209, dtype: object
210 Name      Quagsire
Type 1       Water
Name: 210, dtype: object
211 Name       Espeon
Type 1    Psychic
Name: 211, dtype: object
212 Name      Umbreon
Type 1       Dark
Name: 212, dtype: object
213 Name      Murkrow
Type 1       Dark
Name: 213, dtype: object
214 Name      Slowking
Type 1       Water
Name: 214, dtype: object
215 Name      Misdreavus
Type 1         Ghost
Name: 215, dtype: object
216 Name        Unown
Type 1    Psychic
Name: 216, dtype: object
217 Name      Wobbuffet
Type 1      Psychic
Name: 217, dtype: object
218 Name      Girafarig
Type 1       Normal
Name: 218, dtype: object
219 Name      Pineco
Type 1       Bug
Name: 219, dtype: object
220 Name      Forretress
Type 1           Bug
Name: 220, dtype: object
221 Name      Dunsparce
Type 1       Normal
Name: 221, dtype: object
222 Name      Gligar
Type 1    Ground
Name: 222, dtype: object
223 Name      Steelix
Type 1      Steel
Name: 223, dtype: object
224 Name      SteelixMega Steelix
Type 1                  Steel
Name: 224, dtype: object
225 Name      Snubbull
Type 1       Fairy
Name: 225, dtype: object
226 Name      Granbull
Type 1       Fairy
Name: 226, dtype: object
227 Name      Qwilfish
Type 1       Water
Name: 227, dtype: object
228 Name      Scizor
Type 1       Bug
Name: 228, dtype: object
229 Name      ScizorMega Scizor
Type 1                  Bug
Name: 229, dtype: object
230 Name      Shuckle
Type 1        Bug
Name: 230, dtype: object
231 Name      Heracross
Type 1          Bug
Name: 231, dtype: object
232 Name      HeracrossMega Heracross
Type 1                        Bug
Name: 232, dtype: object
233 Name      Sneasel
Type 1       Dark
Name: 233, dtype: object
234 Name      Teddiursa
Type 1       Normal
Name: 234, dtype: object
235 Name      Ursaring
Type 1      Normal
Name: 235, dtype: object
236 Name      Slugma
Type 1      Fire
Name: 236, dtype: object
237 Name      Magcargo
Type 1        Fire
Name: 237, dtype: object
238 Name      Swinub
Type 1       Ice
Name: 238, dtype: object
239 Name      Piloswine
Type 1          Ice
Name: 239, dtype: object
240 Name      Corsola
Type 1      Water
Name: 240, dtype: object
241 Name      Remoraid
Type 1       Water
Name: 241, dtype: object
242 Name      Octillery
Type 1        Water
Name: 242, dtype: object
243 Name      Delibird
Type 1         Ice
Name: 243, dtype: object
244 Name      Mantine
Type 1      Water
Name: 244, dtype: object
245 Name      Skarmory
Type 1       Steel
Name: 245, dtype: object
246 Name      Houndour
Type 1        Dark
Name: 246, dtype: object
247 Name      Houndoom
Type 1        Dark
Name: 247, dtype: object
248 Name      HoundoomMega Houndoom
Type 1                     Dark
Name: 248, dtype: object
249 Name      Kingdra
Type 1      Water
Name: 249, dtype: object
250 Name      Phanpy
Type 1    Ground
Name: 250, dtype: object
251 Name      Donphan
Type 1     Ground
Name: 251, dtype: object
252 Name      Porygon2
Type 1      Normal
Name: 252, dtype: object
253 Name      Stantler
Type 1      Normal
Name: 253, dtype: object
254 Name      Smeargle
Type 1      Normal
Name: 254, dtype: object
255 Name       Tyrogue
Type 1    Fighting
Name: 255, dtype: object
256 Name      Hitmontop
Type 1     Fighting
Name: 256, dtype: object
257 Name      Smoochum
Type 1         Ice
Name: 257, dtype: object
258 Name        Elekid
Type 1    Electric
Name: 258, dtype: object
259 Name      Magby
Type 1     Fire
Name: 259, dtype: object
260 Name      Miltank
Type 1     Normal
Name: 260, dtype: object
261 Name      Blissey
Type 1     Normal
Name: 261, dtype: object
262 Name        Raikou
Type 1    Electric
Name: 262, dtype: object
263 Name      Entei
Type 1     Fire
Name: 263, dtype: object
264 Name      Suicune
Type 1      Water
Name: 264, dtype: object
265 Name      Larvitar
Type 1        Rock

Name: 265, dtype: object
266 Name      Pupitar
Type 1       Rock
Name: 266, dtype: object
267 Name      Tyranitar
Type 1         Rock
Name: 267, dtype: object
268 Name      TyranitarMega Tyranitar
Type 1                       Rock
Name: 268, dtype: object
269 Name        Lugia
Type 1    Psychic
Name: 269, dtype: object
270 Name      Ho-oh
Type 1     Fire
Name: 270, dtype: object
271 Name       Celebi
Type 1    Psychic
Name: 271, dtype: object
272 Name      Treecko
Type 1      Grass
Name: 272, dtype: object
273 Name      Grovyle
Type 1      Grass
Name: 273, dtype: object
274 Name      Sceptile
Type 1       Grass
Name: 274, dtype: object
275 Name      SceptileMega Sceptile
Type 1                    Grass
Name: 275, dtype: object
276 Name      Torchic
Type 1       Fire
Name: 276, dtype: object
277 Name      Combusken
Type 1         Fire
Name: 277, dtype: object
278 Name      Blaziken
Type 1        Fire
Name: 278, dtype: object
279 Name      BlazikenMega Blaziken
Type 1                     Fire
Name: 279, dtype: object
280 Name      Mudkip
Type 1     Water
Name: 280, dtype: object
281 Name      Marshtomp
Type 1        Water
Name: 281, dtype: object
282 Name      Swampert
Type 1       Water
Name: 282, dtype: object
283 Name      SwampertMega Swampert
Type 1                    Water
Name: 283, dtype: object
284 Name      Poochyena
Type 1         Dark
Name: 284, dtype: object
285 Name      Mightyena
Type 1         Dark
Name: 285, dtype: object
286 Name      Zigzagoon
Type 1       Normal
Name: 286, dtype: object
287 Name      Linoone
Type 1     Normal
Name: 287, dtype: object
288 Name      Wurmple
Type 1        Bug
Name: 288, dtype: object
289 Name      Silcoon
Type 1        Bug
Name: 289, dtype: object
290 Name      Beautifly
Type 1          Bug
Name: 290, dtype: object
291 Name      Cascoon
Type 1        Bug
Name: 291, dtype: object
292 Name      Dustox
Type 1       Bug
Name: 292, dtype: object
293 Name      Lotad
Type 1    Water
Name: 293, dtype: object
294 Name      Lombre
Type 1     Water
Name: 294, dtype: object
295 Name      Ludicolo
Type 1       Water
Name: 295, dtype: object
296 Name      Seedot
Type 1     Grass
Name: 296, dtype: object
297 Name      Nuzleaf
Type 1      Grass
Name: 297, dtype: object
298 Name      Shiftry
Type 1      Grass
Name: 298, dtype: object
299 Name      Taillow
Type 1     Normal
Name: 299, dtype: object
300 Name      Swellow
Type 1     Normal
Name: 300, dtype: object
301 Name      Wingull
Type 1      Water
Name: 301, dtype: object
302 Name      Pelipper
Type 1       Water
Name: 302, dtype: object
303 Name        Ralts
Type 1    Psychic
Name: 303, dtype: object
304 Name       Kirlia
Type 1    Psychic
Name: 304, dtype: object
305 Name      Gardevoir
Type 1      Psychic
Name: 305, dtype: object
306 Name      GardevoirMega Gardevoir
Type 1                    Psychic
Name: 306, dtype: object
307 Name      Surskit
Type 1        Bug
Name: 307, dtype: object
308 Name      Masquerain
Type 1           Bug
Name: 308, dtype: object
309 Name      Shroomish
Type 1        Grass
Name: 309, dtype: object
310 Name      Breloom
Type 1      Grass
Name: 310, dtype: object
311 Name      Slakoth
Type 1     Normal
Name: 311, dtype: object
312 Name      Vigoroth
Type 1      Normal
Name: 312, dtype: object
313 Name      Slaking
Type 1     Normal
Name: 313, dtype: object
314 Name      Nincada
Type 1        Bug
Name: 314, dtype: object
315 Name      Ninjask
Type 1        Bug
Name: 315, dtype: object
316 Name      Shedinja
Type 1         Bug
Name: 316, dtype: object
317 Name      Whismur
Type 1     Normal
Name: 317, dtype: object
318 Name      Loudred
Type 1     Normal
Name: 318, dtype: object
319 Name      Exploud
Type 1     Normal
Name: 319, dtype: object
320 Name      Makuhita
Type 1    Fighting
Name: 320, dtype: object
321 Name      Hariyama
Type 1    Fighting
Name: 321, dtype: object
322 Name      Azurill
Type 1     Normal
Name: 322, dtype: object
323 Name      Nosepass
Type 1        Rock
Name: 323, dtype: object
324 Name      Skitty
Type 1    Normal
Name: 324, dtype: object
325 Name      Delcatty
Type 1      Normal
Name: 325, dtype: object
326 Name      Sableye
Type 1       Dark
Name: 326, dtype: object
327 Name      SableyeMega Sableye
Type 1                   Dark
Name: 327, dtype: object
328 Name      Mawile
Type 1     Steel
Name: 328, dtype: object
329 Name      MawileMega Mawile
Type 1                Steel
Name: 329, dtype: object
330 Name       Aron
Type 1    Steel
Name: 330, dtype: object
331 Name      Lairon
Type 1     Steel
Name: 331, dtype: object
332 Name      Aggron
Type 1     Steel
Name: 332, dtype: object
333 Name      AggronMega Aggron
Type 1                Steel
Name: 333, dtype: object
334 Name      Meditite
Type 1    Fighting
Name: 334, dtype: object
335 Name      Medicham
Type 1    Fighting
Name: 335, dtype: object
336 Name      MedichamMega Medicham
Type 1                 Fighting
Name: 336, dtype: object
337 Name      Electrike
Type 1     Electric
Name: 337, dtype: object
338 Name      Manectric
Type 1     Electric
Name: 338, dtype: object
339 Name      ManectricMega Manectric
Type 1                   Electric
Name: 339, dtype: object
340 Name        Plusle
Type 1    Electric
Name: 340, dtype: object
341 Name         Minun
Type 1    Electric
Name: 341, dtype: object
342 Name      Volbeat
Type 1        Bug
Name: 342, dtype: object
343 Name      Illumise
Type 1         Bug
Name: 343, dtype: object
344 Name      Roselia
Type 1      Grass
Name: 344, dtype: object
345 Name      Gulpin
Type 1    Poison
Name: 345, dtype: object
346 Name      Swalot
Type 1    Poison
Name: 346, dtype: object
347 Name      Carvanha
Type 1       Water
Name: 347, dtype: object
348 Name      Sharpedo
Type 1       Water
Name: 348, dtype: object
349 Name      SharpedoMega Sharpedo
Type 1                    Water
Name: 349, dtype: object
350 Name      Wailmer
Type 1      Water
Name: 350, dtype: object
351 Name      Wailord
Type 1      Water
Name: 351, dtype: object
352 Name      Numel
Type 1     Fire
Name: 352, dtype: object
353 Name      Camerupt
Type 1        Fire
Name: 353, dtype: object
354 Name      CameruptMega Camerupt
Type 1                     Fire
Name: 354, dtype: object
355 Name      Torkoal
Type 1       Fire
Name: 355, dtype: object
356 Name       Spoink
Type 1    Psychic
Name: 356, dtype: object
357 Name      Grumpig
Type 1    Psychic
Name: 357, dtype: object
358 Name      Spinda
Type 1    Normal
Name: 358, dtype: object
359 Name      Trapinch
Type 1      Ground
Name: 359, dtype: object
360 Name      Vibrava
Type 1     Ground
Name: 360, dtype: object
361 Name      Flygon
Type 1    Ground
Name: 361, dtype: object
362 Name      Cacnea
Type 1     Grass
Name: 362, dtype: object
363 Name      Cacturne
Type 1       Grass
Name: 363, dtype: object
364 Name      Swablu
Type 1    Normal
Name: 364, dtype: object
365 Name      Altaria
Type 1     Dragon
Name: 365, dtype: object
366 Name      AltariaMega Altaria
Type 1                 Dragon
Name: 366, dtype: object
367 Name      Zangoose
Type 1      Normal
Name: 367, dtype: object
368 Name      Seviper
Type 1     Poison
Name: 368, dtype: object
369 Name      Lunatone
Type 1        Rock
Name: 369, dtype: object
370 Name      Solrock
Type 1       Rock
Name: 370, dtype: object
371 Name      Barboach
Type 1       Water
Name: 371, dtype: object
372 Name      Whiscash
Type 1       Water
Name: 372, dtype: object
373 Name      Corphish
Type 1       Water
Name: 373, dtype: object
374 Name      Crawdaunt
Type 1        Water
Name: 374, dtype: object
375 Name      Baltoy
Type 1    Ground
Name: 375, dtype: object
376 Name      Claydol
Type 1     Ground
Name: 376, dtype: object
377 Name      Lileep
Type 1      Rock
Name: 377, dtype: object
378 Name      Cradily
Type 1       Rock
Name: 378, dtype: object
379 Name      Anorith
Type 1       Rock
Name: 379, dtype: object
380 Name      Armaldo
Type 1       Rock
Name: 380, dtype: object
381 Name      Feebas
Type 1     Water
Name: 381, dtype: object
382 Name      Milotic
Type 1      Water
Name: 382, dtype: object
383 Name      Castform
Type 1      Normal
Name: 383, dtype: object
384 Name      Kecleon
Type 1     Normal
Name: 384, dtype: object
385 Name      Shuppet
Type 1      Ghost
Name: 385, dtype: object
386 Name      Banette
Type 1      Ghost
Name: 386, dtype: object
387 Name      BanetteMega Banette
Type 1                  Ghost
Name: 387, dtype: object
388 Name      Duskull
Type 1      Ghost

Name: 388, dtype: object
389 Name      Dusclops
Type 1       Ghost
Name: 389, dtype: object
390 Name      Tropius
Type 1      Grass
Name: 390, dtype: object
391 Name      Chimecho
Type 1     Psychic
Name: 391, dtype: object
392 Name      Absol
Type 1     Dark
Name: 392, dtype: object
393 Name      AbsolMega Absol
Type 1               Dark
Name: 393, dtype: object
394 Name       Wynaut
Type 1    Psychic
Name: 394, dtype: object
395 Name      Snorunt
Type 1        Ice
Name: 395, dtype: object
396 Name      Glalie
Type 1       Ice
Name: 396, dtype: object
397 Name      GlalieMega Glalie
Type 1                  Ice
Name: 397, dtype: object
398 Name      Spheal
Type 1       Ice
Name: 398, dtype: object
399 Name      Sealeo
Type 1       Ice
Name: 399, dtype: object
400 Name      Walrein
Type 1        Ice
Name: 400, dtype: object
401 Name      Clamperl
Type 1       Water
Name: 401, dtype: object
402 Name      Huntail
Type 1      Water
Name: 402, dtype: object
403 Name      Gorebyss
Type 1       Water
Name: 403, dtype: object
404 Name      Relicanth
Type 1        Water
Name: 404, dtype: object
405 Name      Luvdisc
Type 1      Water
Name: 405, dtype: object
406 Name       Bagon
Type 1    Dragon
Name: 406, dtype: object
407 Name      Shelgon
Type 1     Dragon
Name: 407, dtype: object
408 Name      Salamence
Type 1       Dragon
Name: 408, dtype: object
409 Name      SalamenceMega Salamence
Type 1                     Dragon
Name: 409, dtype: object
410 Name      Beldum
Type 1     Steel
Name: 410, dtype: object
411 Name      Metang
Type 1     Steel
Name: 411, dtype: object
412 Name      Metagross
Type 1        Steel
Name: 412, dtype: object
413 Name      MetagrossMega Metagross
Type 1                      Steel
Name: 413, dtype: object
414 Name      Regirock
Type 1        Rock
Name: 414, dtype: object
415 Name      Regice
Type 1       Ice
Name: 415, dtype: object
416 Name      Registeel
Type 1        Steel
Name: 416, dtype: object
417 Name      Latias
Type 1    Dragon
Name: 417, dtype: object
418 Name      LatiasMega Latias
Type 1               Dragon
Name: 418, dtype: object
419 Name      Latios
Type 1    Dragon
Name: 419, dtype: object
420 Name      LatiosMega Latios
Type 1               Dragon
Name: 420, dtype: object
421 Name      Kyogre
Type 1     Water
Name: 421, dtype: object
422 Name      KyogrePrimal Kyogre
Type 1                  Water
Name: 422, dtype: object
423 Name      Groudon
Type 1     Ground
Name: 423, dtype: object
424 Name      GroudonPrimal Groudon
Type 1                   Ground
Name: 424, dtype: object
425 Name      Rayquaza
Type 1      Dragon
Name: 425, dtype: object
426 Name      RayquazaMega Rayquaza
Type 1                   Dragon
Name: 426, dtype: object
427 Name      Jirachi
Type 1      Steel
Name: 427, dtype: object
428 Name      DeoxysNormal Forme
Type 1               Psychic
Name: 428, dtype: object
429 Name      DeoxysAttack Forme
Type 1               Psychic
Name: 429, dtype: object
430 Name      DeoxysDefense Forme
Type 1                Psychic
Name: 430, dtype: object
431 Name      DeoxysSpeed Forme
Type 1              Psychic
Name: 431, dtype: object
432 Name      Turtwig
Type 1      Grass
Name: 432, dtype: object
433 Name      Grotle
Type 1     Grass
Name: 433, dtype: object
434 Name      Torterra
Type 1       Grass
Name: 434, dtype: object
435 Name      Chimchar
Type 1        Fire
Name: 435, dtype: object
436 Name      Monferno
Type 1        Fire
Name: 436, dtype: object
437 Name      Infernape
Type 1         Fire
Name: 437, dtype: object
438 Name      Piplup
Type 1     Water
Name: 438, dtype: object
439 Name      Prinplup
Type 1       Water
Name: 439, dtype: object
440 Name      Empoleon
Type 1       Water
Name: 440, dtype: object
441 Name      Starly
Type 1    Normal
Name: 441, dtype: object
442 Name      Staravia
Type 1      Normal
Name: 442, dtype: object
443 Name      Staraptor
Type 1       Normal
Name: 443, dtype: object
444 Name      Bidoof
Type 1    Normal
Name: 444, dtype: object
445 Name      Bibarel
Type 1     Normal
Name: 445, dtype: object
446 Name      Kricketot
Type 1          Bug
Name: 446, dtype: object
447 Name      Kricketune
Type 1           Bug
Name: 447, dtype: object
448 Name         Shinx
Type 1    Electric
Name: 448, dtype: object
449 Name         Luxio
Type 1    Electric
Name: 449, dtype: object
450 Name        Luxray
Type 1    Electric
Name: 450, dtype: object
451 Name      Budew
Type 1    Grass
Name: 451, dtype: object
452 Name      Roserade
Type 1       Grass
Name: 452, dtype: object
453 Name      Cranidos
Type 1        Rock
Name: 453, dtype: object
454 Name      Rampardos
Type 1         Rock
Name: 454, dtype: object
455 Name      Shieldon
Type 1        Rock
Name: 455, dtype: object
456 Name      Bastiodon
Type 1         Rock
Name: 456, dtype: object
457 Name      Burmy
Type 1      Bug
Name: 457, dtype: object
458 Name      WormadamPlant Cloak
Type 1                    Bug
Name: 458, dtype: object
459 Name      WormadamSandy Cloak
Type 1                    Bug
Name: 459, dtype: object
460 Name      WormadamTrash Cloak
Type 1                    Bug
Name: 460, dtype: object
461 Name      Mothim
Type 1       Bug
Name: 461, dtype: object
462 Name      Combee
Type 1       Bug
Name: 462, dtype: object
463 Name      Vespiquen
Type 1          Bug
Name: 463, dtype: object
464 Name      Pachirisu
Type 1     Electric
Name: 464, dtype: object
465 Name      Buizel
Type 1     Water
Name: 465, dtype: object
466 Name      Floatzel
Type 1       Water
Name: 466, dtype: object
467 Name      Cherubi
Type 1      Grass
Name: 467, dtype: object
468 Name      Cherrim
Type 1      Grass
Name: 468, dtype: object
469 Name      Shellos
Type 1      Water
Name: 469, dtype: object
470 Name      Gastrodon
Type 1        Water
Name: 470, dtype: object
471 Name      Ambipom
Type 1     Normal
Name: 471, dtype: object
472 Name      Drifloon
Type 1       Ghost
Name: 472, dtype: object
473 Name      Drifblim
Type 1       Ghost
Name: 473, dtype: object
474 Name      Buneary
Type 1     Normal
Name: 474, dtype: object
475 Name      Lopunny
Type 1     Normal
Name: 475, dtype: object
476 Name      LopunnyMega Lopunny
Type 1                 Normal
Name: 476, dtype: object
477 Name      Mismagius
Type 1        Ghost
Name: 477, dtype: object
478 Name      Honchkrow
Type 1         Dark
Name: 478, dtype: object
479 Name      Glameow
Type 1     Normal
Name: 479, dtype: object
480 Name      Purugly
Type 1     Normal
Name: 480, dtype: object
481 Name      Chingling
Type 1      Psychic
Name: 481, dtype: object
482 Name      Stunky
Type 1    Poison
Name: 482, dtype: object
483 Name      Skuntank
Type 1      Poison
Name: 483, dtype: object
484 Name      Bronzor
Type 1      Steel
Name: 484, dtype: object
485 Name      Bronzong
Type 1       Steel
Name: 485, dtype: object
486 Name      Bonsly
Type 1      Rock
Name: 486, dtype: object
487 Name      Mime Jr.
Type 1     Psychic
Name: 487, dtype: object
488 Name      Happiny
Type 1     Normal
Name: 488, dtype: object
489 Name      Chatot
Type 1    Normal
Name: 489, dtype: object
490 Name      Spiritomb
Type 1        Ghost
Name: 490, dtype: object
491 Name       Gible
Type 1    Dragon
Name: 491, dtype: object
492 Name      Gabite
Type 1    Dragon
Name: 492, dtype: object
493 Name      Garchomp
Type 1      Dragon
Name: 493, dtype: object
494 Name      GarchompMega Garchomp
Type 1                   Dragon
Name: 494, dtype: object
495 Name      Munchlax
Type 1      Normal
Name: 495, dtype: object
496 Name         Riolu
Type 1    Fighting
Name: 496, dtype: object
497 Name       Lucario
Type 1    Fighting
Name: 497, dtype: object
498 Name      LucarioMega Lucario
Type 1               Fighting
Name: 498, dtype: object
499 Name      Hippopotas
Type 1        Ground
Name: 499, dtype: object
500 Name      Hippowdon
Type 1       Ground
Name: 500, dtype: object
501 Name      Skorupi
Type 1     Poison
Name: 501, dtype: object
502 Name      Drapion
Type 1     Poison
Name: 502, dtype: object
503 Name      Croagunk
Type 1      Poison
Name: 503, dtype: object
504 Name      Toxicroak
Type 1       Poison
Name: 504, dtype: object
505 Name      Carnivine
Type 1        Grass
Name: 505, dtype: object
506 Name      Finneon
Type 1      Water
Name: 506, dtype: object
507 Name      Lumineon
Type 1       Water
Name: 507, dtype: object
508 Name      Mantyke
Type 1      Water
Name: 508, dtype: object
509 Name      Snover
Type 1     Grass
Name: 509, dtype: object
510 Name      Abomasnow
Type 1        Grass
Name: 510, dtype: object
511 Name      AbomasnowMega Abomasnow
Type 1                      Grass
Name: 511, dtype: object
512 Name      Weavile
Type 1       Dark
Name: 512, dtype: object
513 Name      Magnezone
Type 1     Electric
Name: 513, dtype: object
514 Name      Lickilicky
Type 1        Normal
Name: 514, dtype: object
515 Name      Rhyperior
Type 1       Ground
Name: 515, dtype: object
516 Name      Tangrowth
Type 1        Grass
Name: 516, dtype: object
517 Name      Electivire
Type 1      Electric
Name: 517, dtype: object
518 Name      Magmortar
Type 1         Fire
Name: 518, dtype: object
519 Name      Togekiss
Type 1       Fairy
Name: 519, dtype: object
520 Name      Yanmega
Type 1        Bug
Name: 520, dtype: object
521 Name      Leafeon
Type 1      Grass
Name: 521, dtype: object

522 Name      Glaceon
Type 1        Ice
Name: 522, dtype: object
523 Name      Gliscor
Type 1     Ground
Name: 523, dtype: object
524 Name      Mamoswine
Type 1          Ice
Name: 524, dtype: object
525 Name      Porygon-Z
Type 1       Normal
Name: 525, dtype: object
526 Name      Gallade
Type 1    Psychic
Name: 526, dtype: object
527 Name      GalladeMega Gallade
Type 1                Psychic
Name: 527, dtype: object
528 Name      Probopass
Type 1         Rock
Name: 528, dtype: object
529 Name      Dusknoir
Type 1       Ghost
Name: 529, dtype: object
530 Name      Froslass
Type 1         Ice
Name: 530, dtype: object
531 Name         Rotom
Type 1    Electric
Name: 531, dtype: object
532 Name      RotomHeat Rotom
Type 1           Electric
Name: 532, dtype: object
533 Name      RotomWash Rotom
Type 1           Electric
Name: 533, dtype: object
534 Name      RotomFrost Rotom
Type 1            Electric
Name: 534, dtype: object
535 Name      RotomFan Rotom
Type 1          Electric
Name: 535, dtype: object
536 Name      RotomMow Rotom
Type 1          Electric
Name: 536, dtype: object
537 Name         Uxie
Type 1    Psychic
Name: 537, dtype: object
538 Name      Mesprit
Type 1    Psychic
Name: 538, dtype: object
539 Name        Azelf
Type 1    Psychic
Name: 539, dtype: object
540 Name      Dialga
Type 1     Steel
Name: 540, dtype: object
541 Name      Palkia
Type 1     Water
Name: 541, dtype: object
542 Name      Heatran
Type 1       Fire
Name: 542, dtype: object
543 Name      Regigigas
Type 1       Normal
Name: 543, dtype: object
544 Name      GiratinaAltered Forme
Type 1                    Ghost
Name: 544, dtype: object
545 Name      GiratinaOrigin Forme
Type 1                   Ghost
Name: 545, dtype: object
546 Name      Cresselia
Type 1      Psychic
Name: 546, dtype: object
547 Name      Phione
Type 1     Water
Name: 547, dtype: object
548 Name      Manaphy
Type 1      Water
Name: 548, dtype: object
549 Name      Darkrai
Type 1       Dark
Name: 549, dtype: object
550 Name      ShayminLand Forme
Type 1                Grass
Name: 550, dtype: object
551 Name      ShayminSky Forme
Type 1               Grass
Name: 551, dtype: object
552 Name      Arceus
Type 1    Normal
Name: 552, dtype: object
553 Name      Victini
Type 1    Psychic
Name: 553, dtype: object
554 Name      Snivy
Type 1    Grass
Name: 554, dtype: object
555 Name      Servine
Type 1      Grass
Name: 555, dtype: object
556 Name      Serperior
Type 1        Grass
Name: 556, dtype: object
557 Name      Tepig
Type 1     Fire
Name: 557, dtype: object
558 Name      Pignite
Type 1       Fire
Name: 558, dtype: object
559 Name      Emboar
Type 1      Fire
Name: 559, dtype: object
560 Name      Oshawott
Type 1       Water
Name: 560, dtype: object
561 Name      Dewott
Type 1     Water
Name: 561, dtype: object
562 Name      Samurott
Type 1       Water
Name: 562, dtype: object
563 Name      Patrat
Type 1    Normal
Name: 563, dtype: object
564 Name      Watchog
Type 1     Normal
Name: 564, dtype: object
565 Name      Lillipup
Type 1      Normal
Name: 565, dtype: object
566 Name      Herdier
Type 1     Normal
Name: 566, dtype: object
567 Name      Stoutland
Type 1       Normal
Name: 567, dtype: object
568 Name      Purrloin
Type 1        Dark
Name: 568, dtype: object
569 Name      Liepard
Type 1       Dark
Name: 569, dtype: object
570 Name      Pansage
Type 1      Grass
Name: 570, dtype: object
571 Name      Simisage
Type 1       Grass
Name: 571, dtype: object
572 Name      Pansear
Type 1       Fire
Name: 572, dtype: object
573 Name      Simisear
Type 1        Fire
Name: 573, dtype: object
574 Name      Panpour
Type 1      Water
Name: 574, dtype: object
575 Name      Simipour
Type 1       Water
Name: 575, dtype: object
576 Name        Munna
Type 1    Psychic
Name: 576, dtype: object
577 Name      Musharna
Type 1     Psychic
Name: 577, dtype: object
578 Name      Pidove
Type 1    Normal
Name: 578, dtype: object
579 Name      Tranquill
Type 1       Normal
Name: 579, dtype: object
580 Name      Unfezant
Type 1      Normal
Name: 580, dtype: object
581 Name       Blitzle
Type 1    Electric
Name: 581, dtype: object
582 Name      Zebstrika
Type 1     Electric
Name: 582, dtype: object
583 Name      Roggenrola
Type 1          Rock
Name: 583, dtype: object
584 Name      Boldore
Type 1       Rock
Name: 584, dtype: object
585 Name      Gigalith
Type 1        Rock
Name: 585, dtype: object
586 Name       Woobat
Type 1    Psychic
Name: 586, dtype: object
587 Name      Swoobat
Type 1    Psychic
Name: 587, dtype: object
588 Name      Drilbur
Type 1     Ground
Name: 588, dtype: object
589 Name      Excadrill
Type 1       Ground
Name: 589, dtype: object
590 Name      Audino
Type 1    Normal
Name: 590, dtype: object
591 Name      AudinoMega Audino
Type 1               Normal
Name: 591, dtype: object
592 Name       Timburr
Type 1    Fighting
Name: 592, dtype: object
593 Name       Gurdurr
Type 1    Fighting
Name: 593, dtype: object
594 Name      Conkeldurr
Type 1      Fighting
Name: 594, dtype: object
595 Name      Tympole
Type 1      Water
Name: 595, dtype: object
596 Name      Palpitoad
Type 1        Water
Name: 596, dtype: object
597 Name      Seismitoad
Type 1         Water
Name: 597, dtype: object
598 Name         Throh
Type 1    Fighting
Name: 598, dtype: object
599 Name          Sawk
Type 1    Fighting
Name: 599, dtype: object
600 Name      Sewaddle
Type 1         Bug
Name: 600, dtype: object
601 Name      Swadloon
Type 1         Bug
Name: 601, dtype: object
602 Name      Leavanny
Type 1         Bug
Name: 602, dtype: object
603 Name      Venipede
Type 1         Bug
Name: 603, dtype: object
604 Name      Whirlipede
Type 1           Bug
Name: 604, dtype: object
605 Name      Scolipede
Type 1          Bug
Name: 605, dtype: object
606 Name      Cottonee
Type 1       Grass
Name: 606, dtype: object
607 Name      Whimsicott
Type 1         Grass
Name: 607, dtype: object
608 Name      Petilil
Type 1      Grass
Name: 608, dtype: object
609 Name      Lilligant
Type 1        Grass
Name: 609, dtype: object
610 Name      Basculin
Type 1       Water
Name: 610, dtype: object
611 Name      Sandile
Type 1     Ground
Name: 611, dtype: object
612 Name      Krokorok
Type 1      Ground
Name: 612, dtype: object
613 Name      Krookodile
Type 1        Ground
Name: 613, dtype: object
614 Name      Darumaka
Type 1        Fire
Name: 614, dtype: object
615 Name      DarmanitanStandard Mode
Type 1                       Fire
Name: 615, dtype: object
616 Name      DarmanitanZen Mode
Type 1                  Fire
Name: 616, dtype: object
617 Name      Maractus
Type 1       Grass
Name: 617, dtype: object
618 Name      Dwebble
Type 1        Bug
Name: 618, dtype: object
619 Name      Crustle
Type 1        Bug
Name: 619, dtype: object
620 Name      Scraggy
Type 1       Dark
Name: 620, dtype: object
621 Name      Scrafty
Type 1       Dark
Name: 621, dtype: object
622 Name      Sigilyph
Type 1     Psychic
Name: 622, dtype: object
623 Name      Yamask
Type 1     Ghost
Name: 623, dtype: object
624 Name      Cofagrigus
Type 1         Ghost
Name: 624, dtype: object
625 Name      Tirtouga
Type 1       Water
Name: 625, dtype: object
626 Name      Carracosta
Type 1         Water
Name: 626, dtype: object
627 Name      Archen
Type 1      Rock
Name: 627, dtype: object
628 Name      Archeops
Type 1        Rock
Name: 628, dtype: object
629 Name      Trubbish
Type 1      Poison
Name: 629, dtype: object
630 Name      Garbodor
Type 1      Poison
Name: 630, dtype: object
631 Name      Zorua
Type 1     Dark
Name: 631, dtype: object
632 Name      Zoroark
Type 1       Dark
Name: 632, dtype: object
633 Name      Minccino
Type 1      Normal
Name: 633, dtype: object
634 Name      Cinccino
Type 1      Normal
Name: 634, dtype: object
635 Name      Gothita
Type 1    Psychic
Name: 635, dtype: object
636 Name      Gothorita
Type 1      Psychic
Name: 636, dtype: object
637 Name      Gothitelle
Type 1       Psychic
Name: 637, dtype: object
638 Name      Solosis
Type 1    Psychic
Name: 638, dtype: object
639 Name      Duosion
Type 1    Psychic
Name: 639, dtype: object
640 Name      Reuniclus
Type 1      Psychic
Name: 640, dtype: object
641 Name      Ducklett
Type 1       Water
Name: 641, dtype: object
642 Name      Swanna
Type 1     Water
Name: 642, dtype: object
643 Name      Vanillite
Type 1          Ice
Name: 643, dtype: object
644 Name      Vanillish
Type 1          Ice
Name: 644, dtype: object
645 Name      Vanilluxe
Type 1          Ice
Name: 645, dtype: object
646 Name      Deerling
Type 1      Normal
Name: 646, dtype: object
647 Name      Sawsbuck
Type 1      Normal
Name: 647, dtype: object
648 Name        Emolga
Type 1    Electric
Name: 648, dtype: object
649 Name      Karrablast
Type 1           Bug
Name: 649, dtype: object
650 Name      Escavalier
Type 1           Bug
Name: 650, dtype: object
651 Name      Foongus
Type 1      Grass
Name: 651, dtype: object
652 Name      Amoonguss
Type 1        Grass
Name: 652, dtype: object
653 Name      Frillish
Type 1       Water
Name: 653, dtype: object
654 Name      Jellicent
Type 1        Water
Name: 654, dtype: object
655 Name      Alomomola
Type 1        Water
Name: 655, dtype: object
656 Name      Joltik
Type 1       Bug
Name: 656, dtype: object
657 Name      Galvantula
Type 1           Bug
Name: 657, dtype: object
658 Name      Ferroseed
Type 1        Grass
Name: 658, dtype: object
659 Name      Ferrothorn
Type 1         Grass
Name: 659, dtype: object

660 Name      Klink
Type 1    Steel
Name: 660, dtype: object
661 Name      Klang
Type 1    Steel
Name: 661, dtype: object
662 Name      Klinklang
Type 1        Steel
Name: 662, dtype: object
663 Name        Tynamo
Type 1    Electric
Name: 663, dtype: object
664 Name      Eelektrik
Type 1     Electric
Name: 664, dtype: object
665 Name      Eelektross
Type 1      Electric
Name: 665, dtype: object
666 Name       Elgyem
Type 1    Psychic
Name: 666, dtype: object
667 Name      Beheeyem
Type 1     Psychic
Name: 667, dtype: object
668 Name      Litwick
Type 1      Ghost
Name: 668, dtype: object
669 Name      Lampent
Type 1      Ghost
Name: 669, dtype: object
670 Name      Chandelure
Type 1         Ghost
Name: 670, dtype: object
671 Name        Axew
Type 1    Dragon
Name: 671, dtype: object
672 Name      Fraxure
Type 1     Dragon
Name: 672, dtype: object
673 Name      Haxorus
Type 1     Dragon
Name: 673, dtype: object
674 Name      Cubchoo
Type 1        Ice
Name: 674, dtype: object
675 Name      Beartic
Type 1        Ice
Name: 675, dtype: object
676 Name      Cryogonal
Type 1          Ice
Name: 676, dtype: object
677 Name      Shelmet
Type 1        Bug
Name: 677, dtype: object
678 Name      Accelgor
Type 1         Bug
Name: 678, dtype: object
679 Name      Stunfisk
Type 1      Ground
Name: 679, dtype: object
680 Name       Mienfoo
Type 1    Fighting
Name: 680, dtype: object
681 Name      Mienshao
Type 1    Fighting
Name: 681, dtype: object
682 Name      Druddigon
Type 1       Dragon
Name: 682, dtype: object
683 Name      Golett
Type 1    Ground
Name: 683, dtype: object
684 Name      Golurk
Type 1    Ground
Name: 684, dtype: object
685 Name      Pawniard
Type 1        Dark
Name: 685, dtype: object
686 Name      Bisharp
Type 1       Dark
Name: 686, dtype: object
687 Name      Bouffalant
Type 1        Normal
Name: 687, dtype: object
688 Name      Rufflet
Type 1     Normal
Name: 688, dtype: object
689 Name      Braviary
Type 1      Normal
Name: 689, dtype: object
690 Name      Vullaby
Type 1       Dark
Name: 690, dtype: object
691 Name      Mandibuzz
Type 1         Dark
Name: 691, dtype: object
692 Name      Heatmor
Type 1       Fire
Name: 692, dtype: object
693 Name      Durant
Type 1       Bug
Name: 693, dtype: object
694 Name      Deino
Type 1     Dark
Name: 694, dtype: object
695 Name      Zweilous
Type 1        Dark
Name: 695, dtype: object
696 Name      Hydreigon
Type 1         Dark
Name: 696, dtype: object
697 Name      Larvesta
Type 1         Bug
Name: 697, dtype: object
698 Name      Volcarona
Type 1          Bug
Name: 698, dtype: object
699 Name      Cobalion
Type 1       Steel
Name: 699, dtype: object
700 Name      Terrakion
Type 1         Rock
Name: 700, dtype: object
701 Name      Virizion
Type 1       Grass
Name: 701, dtype: object
702 Name      TornadusIncarnate Forme
Type 1                     Flying
Name: 702, dtype: object
703 Name      TornadusTherian Forme
Type 1                   Flying
Name: 703, dtype: object
704 Name      ThundurusIncarnate Forme
Type 1                    Electric
Name: 704, dtype: object
705 Name      ThundurusTherian Forme
Type 1                  Electric
Name: 705, dtype: object
706 Name      Reshiram
Type 1      Dragon
Name: 706, dtype: object
707 Name      Zekrom
Type 1    Dragon
Name: 707, dtype: object
708 Name      LandorusIncarnate Forme
Type 1                     Ground
Name: 708, dtype: object
709 Name      LandorusTherian Forme
Type 1                   Ground
Name: 709, dtype: object
710 Name      Kyurem
Type 1    Dragon
Name: 710, dtype: object
711 Name      KyuremBlack Kyurem
Type 1                Dragon
Name: 711, dtype: object
712 Name      KyuremWhite Kyurem
Type 1                Dragon
Name: 712, dtype: object
713 Name      KeldeoOrdinary Forme
Type 1                   Water
Name: 713, dtype: object
714 Name      KeldeoResolute Forme
Type 1                   Water
Name: 714, dtype: object
715 Name      MeloettaAria Forme
Type 1                Normal
Name: 715, dtype: object
716 Name      MeloettaPirouette Forme
Type 1                     Normal
Name: 716, dtype: object
717 Name      Genesect
Type 1         Bug
Name: 717, dtype: object
718 Name      Chespin
Type 1      Grass
Name: 718, dtype: object
719 Name      Quilladin
Type 1        Grass
Name: 719, dtype: object
720 Name      Chesnaught
Type 1         Grass
Name: 720, dtype: object
721 Name      Fennekin
Type 1        Fire
Name: 721, dtype: object
722 Name      Braixen
Type 1       Fire
Name: 722, dtype: object
723 Name      Delphox
Type 1       Fire
Name: 723, dtype: object
724 Name      Froakie
Type 1      Water
Name: 724, dtype: object
725 Name      Frogadier
Type 1        Water
Name: 725, dtype: object
726 Name      Greninja
Type 1       Water
Name: 726, dtype: object
727 Name      Bunnelby
Type 1      Normal
Name: 727, dtype: object
728 Name      Diggersby
Type 1       Normal
Name: 728, dtype: object
729 Name      Fletchling
Type 1        Normal
Name: 729, dtype: object
730 Name      Fletchinder
Type 1           Fire
Name: 730, dtype: object
731 Name      Talonflame
Type 1          Fire
Name: 731, dtype: object
732 Name      Scatterbug
Type 1           Bug
Name: 732, dtype: object
733 Name      Spewpa
Type 1       Bug
Name: 733, dtype: object
734 Name      Vivillon
Type 1         Bug
Name: 734, dtype: object
735 Name      Litleo
Type 1      Fire
Name: 735, dtype: object
736 Name      Pyroar
Type 1      Fire
Name: 736, dtype: object
737 Name      Flabébé
Type 1      Fairy
Name: 737, dtype: object
738 Name      Floette
Type 1      Fairy
Name: 738, dtype: object
739 Name      Florges
Type 1      Fairy
Name: 739, dtype: object
740 Name      Skiddo
Type 1     Grass
Name: 740, dtype: object
741 Name      Gogoat
Type 1     Grass
Name: 741, dtype: object
742 Name       Pancham
Type 1    Fighting
Name: 742, dtype: object
743 Name       Pangoro
Type 1    Fighting
Name: 743, dtype: object
744 Name      Furfrou
Type 1     Normal
Name: 744, dtype: object
745 Name       Espurr
Type 1    Psychic
Name: 745, dtype: object
746 Name      MeowsticMale
Type 1         Psychic
Name: 746, dtype: object
747 Name      MeowsticFemale
Type 1           Psychic
Name: 747, dtype: object
748 Name      Honedge
Type 1      Steel
Name: 748, dtype: object
749 Name      Doublade
Type 1       Steel
Name: 749, dtype: object
750 Name      AegislashBlade Forme
Type 1                   Steel
Name: 750, dtype: object
751 Name      AegislashShield Forme
Type 1                    Steel
Name: 751, dtype: object
752 Name      Spritzee
Type 1       Fairy
Name: 752, dtype: object
753 Name      Aromatisse
Type 1         Fairy
Name: 753, dtype: object
754 Name      Swirlix
Type 1      Fairy
Name: 754, dtype: object
755 Name      Slurpuff
Type 1       Fairy
Name: 755, dtype: object
756 Name      Inkay
Type 1     Dark
Name: 756, dtype: object
757 Name      Malamar
Type 1       Dark
Name: 757, dtype: object
758 Name      Binacle
Type 1       Rock
Name: 758, dtype: object
759 Name      Barbaracle
Type 1          Rock
Name: 759, dtype: object
760 Name      Skrelp
Type 1    Poison
Name: 760, dtype: object
761 Name      Dragalge
Type 1      Poison
Name: 761, dtype: object
762 Name      Clauncher
Type 1        Water
Name: 762, dtype: object
763 Name      Clawitzer
Type 1        Water
Name: 763, dtype: object
764 Name      Helioptile
Type 1      Electric
Name: 764, dtype: object
765 Name      Heliolisk
Type 1     Electric
Name: 765, dtype: object
766 Name      Tyrunt
Type 1      Rock
Name: 766, dtype: object
767 Name      Tyrantrum
Type 1         Rock
Name: 767, dtype: object
768 Name      Amaura
Type 1      Rock
Name: 768, dtype: object
769 Name      Aurorus
Type 1       Rock
Name: 769, dtype: object
770 Name      Sylveon
Type 1      Fairy
Name: 770, dtype: object
771 Name      Hawlucha
Type 1    Fighting
Name: 771, dtype: object
772 Name       Dedenne
Type 1    Electric
Name: 772, dtype: object
773 Name      Carbink
Type 1       Rock
Name: 773, dtype: object
774 Name       Goomy
Type 1    Dragon
Name: 774, dtype: object
775 Name      Sliggoo
Type 1     Dragon
Name: 775, dtype: object
776 Name      Goodra
Type 1    Dragon
Name: 776, dtype: object
777 Name      Klefki
Type 1     Steel
Name: 777, dtype: object
778 Name      Phantump
Type 1       Ghost
Name: 778, dtype: object
779 Name      Trevenant
Type 1        Ghost
Name: 779, dtype: object
780 Name      PumpkabooAverage Size
Type 1                    Ghost
Name: 780, dtype: object
781 Name      PumpkabooSmall Size
Type 1                  Ghost
Name: 781, dtype: object
782 Name      PumpkabooLarge Size
Type 1                  Ghost
Name: 782, dtype: object
783 Name      PumpkabooSuper Size
Type 1                  Ghost
Name: 783, dtype: object
784 Name      GourgeistAverage Size
Type 1                    Ghost
Name: 784, dtype: object
785 Name      GourgeistSmall Size
Type 1                  Ghost
Name: 785, dtype: object
786 Name      GourgeistLarge Size
Type 1                  Ghost
Name: 786, dtype: object
787 Name      GourgeistSuper Size
Type 1                  Ghost
Name: 787, dtype: object
788 Name      Bergmite
Type 1         Ice
Name: 788, dtype: object
789 Name      Avalugg
Type 1        Ice
Name: 789, dtype: object
790 Name      Noibat
Type 1    Flying
Name: 790, dtype: object
791 Name      Noivern
Type 1     Flying
Name: 791, dtype: object
792 Name      Xerneas
Type 1      Fairy
Name: 792, dtype: object
793 Name      Yveltal
Type 1       Dark
Name: 793, dtype: object
794 Name      Zygarde50% Forme
Type 1              Dragon
Name: 794, dtype: object
795 Name      Diancie
Type 1       Rock
Name: 795, dtype: object
796 Name      DiancieMega Diancie
Type 1                   Rock
Name: 796, dtype: object
797 Name      HoopaHoopa Confined
Type 1                Psychic
Name: 797, dtype: object
798 Name      HoopaHoopa Unbound
Type 1               Psychic
Name: 798, dtype: object
799 Name      Volcanion
Type 1         Fire
Name: 799, dtype: object

In [110]:
df.loc[df['Type 1']=='Fire']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [111]:
df.loc[df['Type 1']=='Rock']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
80,74,Geodude,Rock,Ground,40,80,100,30,30,20,1,False
81,75,Graveler,Rock,Ground,55,95,115,45,45,35,1,False
82,76,Golem,Rock,Ground,80,120,130,55,65,45,1,False
103,95,Onix,Rock,Ground,35,45,160,30,45,70,1,False
149,138,Omanyte,Rock,Water,35,40,100,90,55,35,1,False
150,139,Omastar,Rock,Water,70,60,125,115,70,55,1,False
151,140,Kabuto,Rock,Water,30,80,90,55,45,55,1,False
152,141,Kabutops,Rock,Water,60,115,105,65,70,80,1,False
153,142,Aerodactyl,Rock,Flying,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
200,185,Sudowoodo,Rock,NaN,70,100,115,30,65,30,2,False
265,246,Larvitar,Rock,Ground,50,64,50,45,50,41,2,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
323,299,Nosepass,Rock,NaN,30,45,135,45,90,30,3,False
369,337,Lunatone,Rock,Psychic,70,55,65,95,85,70,3,False
370,338,Solrock,Rock,Psychic,70,95,85,55,65,70,3,False
377,345,Lileep,Rock,Grass,66,41,77,61,87,23,3,False
378,346,Cradily,Rock,Grass,86,81,97,81,107,43,3,False
379,347,Anorith,Rock,Bug,45,95,50,40,50,75,3,False
380,348,Armaldo,Rock,Bug,75,125,100,70,80,45,3,False
414,377,Regirock,Rock,NaN,80,100,200,50,100,50,3,True
453,408,Cranidos,Rock,NaN,67,125,40,30,30,58,4,False
454,409,Rampardos,Rock,NaN,97,165,60,65,50,58,4,False
455,410,Shieldon,Rock,Steel,30,42,118,42,88,30,4,False
456,411,Bastiodon,Rock,Steel,60,52,168,47,138,30,4,False
486,438,Bonsly,Rock,NaN,50,80,95,10,45,10,4,False
528,476,Probopass,Rock,Steel,60,55,145,75,150,40,4,False
583,524,Roggenrola,Rock,NaN,55,75,85,25,25,15,5,False
584,525,Boldore,Rock,NaN,70,105,105,50,40,20,5,False
585,526,Gigalith,Rock,NaN,85,135,130,60,80,25,5,False
627,566,Archen,Rock,Flying,55,112,45,74,45,70,5,False
628,567,Archeops,Rock,Flying,75,140,65,112,65,110,5,False
700,639,Terrakion,Rock,Fighting,91,129,90,72,90,108,5,True
758,688,Binacle,Rock,Water,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False
766,696,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False
767,697,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False
768,698,Amaura,Rock,Ice,77,59,50,67,63,46,6,False
769,699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
773,703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

In [112]:
df.loc[df['Attack']==80]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
47,42,Golbat,Poison,Flying,75,80,70,65,75,90,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
56,51,Dugtrio,Ground,NaN,35,80,50,50,70,120,1,False
61,56,Mankey,Fighting,NaN,40,80,35,35,45,70,1,False
72,66,Machop,Fighting,NaN,70,80,50,35,35,35,1,False
80,74,Geodude,Rock,Ground,40,80,100,30,30,20,1,False
95,88,Grimer,Poison,NaN,80,80,50,40,50,25,1,False
113,105,Marowak,Ground,NaN,60,80,110,50,80,45,1,False
151,140,Kabuto,Rock,Water,30,80,90,55,45,55,1,False
173,159,Croconaw,Water,NaN,65,80,80,59,63,58,2,False
197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False
218,203,Girafarig,Normal,Psychic,70,80,65,90,65,85,2,False
225,209,Snubbull,Fairy,NaN,60,80,50,40,40,30,2,False
234,216,Teddiursa,Normal,NaN,60,80,50,50,50,40,2,False
245,227,Skarmory,Steel,Flying,65,80,140,40,70,70,2,False
252,233,Porygon2,Normal,NaN,85,80,90,105,95,60,2,False
260,241,Miltank,Normal,NaN,95,80,105,40,70,100,2,False
312,288,Vigoroth,Normal,NaN,80,80,80,55,55,90,3,False
373,341,Corphish,Water,NaN,43,80,65,50,35,35,3,False
396,362,Glalie,Ice,NaN,80,80,80,80,80,80,3,False
400,365,Walrein,Ice,Water,110,80,90,95,90,65,3,False
417,380,Latias,Dragon,Psychic,80,80,90,110,130,110,3,True
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False
473,426,Drifblim,Ghost,Flying,150,80,44,90,54,80,4,False
486,438,Bonsly,Rock,NaN,50,80,95,10,45,10,4,False
525,474,Porygon-Z,Normal,NaN,85,80,70,135,75,90,4,False
530,478,Froslass,Ice,Ghost,70,80,70,80,70,110,4,False
547,489,Phione,Water,NaN,80,80,80,80,80,80,4,False
566,507,Herdier,Normal,NaN,65,80,65,35,65,60,5,False
592,532,Timburr,Fighting,NaN,75,80,55,25,35,35,5,False
661,600,Klang,Steel,NaN,60,80,95,70,85,50,5,False
744,676,Furfrou,Normal,NaN,75,80,60,65,90,102,6,False
748,679,Honedge,Steel,Ghost,45,80,100,35,37,28,6,False
755,685,Slurpuff,Fairy,NaN,82,80,86,85,75,72,6,False
777,707,Klefki,Steel,Fairy,57,80,91,80,87,75,6,False

In [113]:
df.loc[df['Type 1']=='Psychic']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
69,64,Kadabra,Psychic,NaN,40,35,30,120,70,105,1,False
70,65,Alakazam,Psychic,NaN,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
104,96,Drowzee,Psychic,NaN,60,48,45,43,90,42,1,False
105,97,Hypno,Psychic,NaN,85,73,70,73,115,67,1,False
131,122,Mr. Mime,Psychic,Fairy,40,45,65,100,120,90,1,False
162,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
165,151,Mew,Psychic,NaN,100,100,100,100,100,100,1,False
191,177,Natu,Psychic,Flying,40,50,45,70,45,70,2,False
192,178,Xatu,Psychic,Flying,65,75,70,95,70,95,2,False
211,196,Espeon,Psychic,NaN,65,65,60,130,95,110,2,False
216,201,Unown,Psychic,NaN,48,72,48,72,48,48,2,False
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
269,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True
271,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False
303,280,Ralts,Psychic,Fairy,28,25,25,45,35,40,3,False
304,281,Kirlia,Psychic,Fairy,38,35,35,65,55,50,3,False
305,282,Gardevoir,Psychic,Fairy,68,65,65,125,115,80,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False
356,325,Spoink,Psychic,NaN,60,25,35,70,80,60,3,False
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,3,False
391,358,Chimecho,Psychic,NaN,65,50,70,95,80,65,3,False
394,360,Wynaut,Psychic,NaN,95,23,48,23,48,23,3,False
428,386,DeoxysNormal Forme,Psychic,NaN,50,150,50,150,50,150,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
430,386,DeoxysDefense Forme,Psychic,NaN,50,70,160,70,160,90,3,True
431,386,DeoxysSpeed Forme,Psychic,NaN,50,95,90,95,90,180,3,True
481,433,Chingling,Psychic,NaN,45,30,50,65,50,45,4,False
487,439,Mime Jr.,Psychic,Fairy,20,25,45,70,90,60,4,False
526,475,Gallade,Psychic,Fighting,68,125,65,65,115,80,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
537,480,Uxie,Psychic,NaN,75,75,130,75,130,95,4,True
538,481,Mesprit,Psychic,NaN,80,105,105,105,105,80,4,True
539,482,Azelf,Psychic,NaN,75,125,70,125,70,115,4,True
546,488,Cresselia,Psychic,NaN,120,70,120,75,130,85,4,False
553,494,Victini,Psychic,Fire,100,100,100,100,100,100,5,True
576,517,Munna,Psychic,NaN,76,25,45,67,55,24,5,False
577,518,Musharna,Psychic,NaN,116,55,85,107,95,29,5,False
586,527,Woobat,Psychic,Flying,55,45,43,55,43,72,5,False
587,528,Swoobat,Psychic,Flying,67,57,55,77,55,114,5,False
622,561,Sigilyph,Psychic,Flying,72,58,80,103,80,97,5,False
635,574,Gothita,Psychic,NaN,45,30,50,55,65,45,5,False
636,575,Gothorita,Psychic,NaN,60,45,70,75,85,55,5,False
637,576,Gothitelle,Psychic,NaN,70,55,95,95,110,65,5,False
638,577,Solosis,Psychic,NaN,45,30,40,105,50,20,5,False
639,578,Duosion,Psychic,NaN,65,40,50,125,60,30,5,False
640,579,Reuniclus,Psychic,NaN,110,65,75,125,85,30,5,False
666,605,Elgyem,Psychic,NaN,55,55,55,85,55,30,5,False
667,606,Beheeyem,Psychic,NaN,75,75,75,125,95,40,5,False
745,677,Espurr,Psychic,NaN,62,48,54,63,60,68,6,False
746,678,MeowsticMale,Psychic,NaN,74,48,76,83,81,104,6,False
747,678,MeowsticFemale,Psychic,NaN,74,48,76,83,81,104,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True

In [114]:
#Gives basic stats like mean, std etc
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [115]:
df.loc[df['HP']==1]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

In [116]:
df.loc[df['HP']==255]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False

In [117]:
#To make it alphabetical order 
df.sort_values('HP', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

In [118]:
df.sort_values(['Type 1','Attack'], ascending=[0,1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
198,183,Marill,Water,Fairy,70,20,50,20,50,40,2,False
508,458,Mantyke,Water,Flying,45,20,50,60,120,50,4,False
293,270,Lotad,Water,Grass,40,30,30,40,50,30,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
650,589,Escavalier,Bug,Steel,70,135,105,60,105,20,5,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False

MAKING CHANGES TO DATA

In [119]:
df['Total']=df['HP']+ df['Attack']+ df['Defense'] + df['Sp. Def'] + df['Speed']

In [120]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,253
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,325
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,425
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,503
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,249

In [121]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Total
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800.000000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375,362.282500
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129,97.955458
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000,150.000000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000,280.000000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000,370.000000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000,431.000000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000,626.000000

In [122]:
df.loc[df['Total']==626]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,626

In [123]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,253
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,325
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,425
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,503
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,249
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,500
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,540
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,450
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,510
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,470

In [124]:
df.drop(columns=['Total'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [125]:
df['Total']=df.iloc[:,4:10].sum(axis=1)

In [126]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [127]:
df['Total']=df.iloc[:,4:10].sum(axis=1)

In [128]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [129]:
df[['Total','HP','Defense']]

     Total  HP  Defense
0      318  45       49
1      405  60       63
2      525  80       83
3      625  80      123
4      309  39       43
..     ...  ..      ...
795    600  50      150
796    700  50      110
797    600  80       60
798    680  80       60
799    600  80      120

[800 rows x 3 columns]

In [130]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [131]:
cols=list(df.columns)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]]

In [132]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [133]:
df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [134]:
df.loc[(df['Type 1']=='Poison') & (df['Type 2']=='Ground')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
36,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False

In [135]:
new_df=df.loc[(df['Type 1']=='Poison')| (df['Type 2']=='Ground') & (df['HP']>75)]

In [136]:
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
34,29,Nidoran (Female),Poison,NaN,275,55,47,52,40,40,41,1,False
35,30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,1,False
36,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False
37,32,Nidoran (Male),Poison,NaN,273,46,57,40,40,40,50,1,False
38,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
47,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False
82,76,Golem,Rock,Ground,495,80,120,130,55,65,45,1,False
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
96,89,Muk,Poison,NaN,500,105,105,75,65,100,50,1,False
117,109,Koffing,Poison,NaN,340,40,65,95,60,45,35,1,False
118,110,Weezing,Poison,NaN,490,65,90,120,85,70,60,1,False
183,169,Crobat,Poison,Flying,535,85,90,80,70,80,130,2,False
210,195,Quagsire,Water,Ground,430,95,85,85,65,65,35,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
282,260,Swampert,Water,Ground,535,100,110,90,85,90,60,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
345,316,Gulpin,Poison,NaN,302,70,43,53,43,53,40,3,False
346,317,Swalot,Poison,NaN,467,100,73,83,73,83,55,3,False
368,336,Seviper,Poison,NaN,458,73,100,60,100,60,65,3,False
372,340,Whiscash,Water,Ground,468,110,78,73,76,71,60,3,False
434,389,Torterra,Grass,Ground,525,95,109,105,75,85,56,4,False
470,423,Gastrodon,Water,Ground,475,111,83,68,92,82,39,4,False
482,434,Stunky,Poison,Dark,329,63,63,47,41,41,74,4,False
483,435,Skuntank,Poison,Dark,479,103,93,67,71,61,84,4,False
493,445,Garchomp,Dragon,Ground,600,108,130,95,80,85,102,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
501,451,Skorupi,Poison,Bug,330,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,500,70,90,110,60,75,95,4,False
503,453,Croagunk,Poison,Fighting,300,48,61,40,61,40,50,4,False
504,454,Toxicroak,Poison,Fighting,490,83,106,65,86,65,85,4,False
524,473,Mamoswine,Ice,Ground,530,110,130,80,70,60,80,4,False
597,537,Seismitoad,Water,Ground,509,105,95,75,85,75,74,5,False
629,568,Trubbish,Poison,NaN,329,50,50,62,40,62,65,5,False
630,569,Garbodor,Poison,NaN,474,80,95,82,60,82,75,5,False
728,660,Diggersby,Normal,Ground,423,85,56,77,50,77,78,6,False
760,690,Skrelp,Poison,Water,320,50,60,60,60,60,30,6,False
761,691,Dragalge,Poison,Dragon,494,65,75,90,97,123,44,6,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [137]:
new_df1=df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison') & (df['HP']>70)]

In [138]:
new_df1

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [139]:
new_df1.to_csv('filtered.csv')

In [140]:
new_df1.reset_index(drop=True)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
2,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
3,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
4,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [141]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [142]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [143]:
import re

In [144]:
df.loc[df['Type 1'].str.contains('Fire|Grass', regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [148]:
df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [151]:
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I , regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

CONDITIONAL CHANGES

In [156]:
df.loc[df['Type 1']=='Fire', 'Type 1']='Flamer'
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,6,True

In [158]:
df.loc[df['Type 1']=='Flamer', 'Type 1']='Smokey'
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Smokey,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Smokey,Water,600,80,110,120,130,90,70,6,True

In [160]:
df.loc[df['Type 1']=='Smokey', 'Type 1']='Fire'
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [162]:
df.loc[df['Type 1']=='Fire','Legendary']=True
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [164]:
df=pd.read_csv('modified.csv')
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [166]:
df.loc[df['Total']>500, ['Generation', 'Legendary']]=['Test 1','Test 2']
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test 1,Test 2
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test 1,Test 2
4,4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test 1,Test 2
796,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test 1,Test 2
797,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test 1,Test 2
798,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test 1,Test 2
799,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,Test 1,Test 2

In [168]:
df=pd.read_csv('modified.csv')
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

AGGREGATE STATISTICS (GROUPBY)

In [170]:
df=pd.read_csv('modified.csv')
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [174]:
df.groupby(['Type 1']).mean().sort_values('Attack',ascending=False)

,Unnamed: 0,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Dragon,521.843750,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Fighting,400.444444,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Ground,392.312500,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Rock,431.840909,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,486.296296,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Dark,507.387097,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,360.942308,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,746.500000,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Poison,278.285714,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Water,333.312500,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,536.281250,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Normal,351.581633,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Grass,380.414286,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ice,465.666667,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Psychic,420.105263,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Bug,368.072464,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Electric,400.590909,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,494.529412,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824

In [173]:
df.groupby(df['Type 2']).mean().sort_values('Defense', ascending=False)

,Unnamed: 0,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 2,,,,,,,,,,,
Rock,381.857143,347.785714,434.642857,68.071429,84.000000,126.857143,51.142857,68.571429,36.000000,3.142857,0.000000
Steel,480.909091,435.636364,485.227273,64.636364,92.590909,104.636364,77.727273,86.272727,59.363636,3.818182,0.045455
Ground,337.971429,307.600000,444.342857,77.228571,89.857143,90.314286,65.542857,66.742857,54.657143,2.942857,0.028571
Dragon,532.111111,482.555556,526.166667,82.166667,94.444444,87.055556,98.500000,83.444444,80.555556,4.166667,0.222222
Psychic,369.969697,337.151515,479.060606,72.212121,74.696970,87.030303,88.030303,87.606061,69.484848,2.939394,0.151515
Ice,486.642857,441.285714,525.714286,90.000000,98.000000,85.642857,92.642857,84.785714,74.642857,3.714286,0.214286
Water,440.000000,400.000000,418.214286,62.714286,70.142857,85.071429,74.500000,68.642857,57.142857,3.428571,0.071429
Fighting,483.346154,438.192308,525.846154,79.461538,112.846154,82.500000,81.269231,82.384615,87.384615,3.923077,0.153846
Ghost,607.071429,551.714286,430.714286,59.142857,84.142857,82.285714,73.214286,78.071429,53.857143,4.785714,0.071429
Fire,529.833333,481.833333,506.250000,71.250000,81.250000,80.166667,110.416667,83.500000,79.666667,4.000000,0.250000
Grass,557.040000,505.400000,408.920000,62.640000,74.160000,80.120000,60.160000,74.520000,57.320000,4.480000,0.000000
Bug,420.000000,382.000000,393.333333,53.333333,90.000000,80.000000,46.666667,61.666667,61.666667,3.333333,0.000000
Fairy,416.173913,379.043478,417.956522,64.304348,61.608696,73.869565,75.000000,81.956522,61.217391,3.565217,0.086957
Dark,455.600000,413.850000,484.400000,75.550000,109.800000,72.050000,81.800000,69.850000,75.350000,3.750000,0.050000
Electric,511.333333,465.666667,455.333333,88.166667,72.666667,68.333333,81.166667,73.500000,71.500000,4.000000,0.166667
Flying,364.402062,331.103093,452.546392,71.391753,80.288660,68.309278,75.628866,71.206186,85.721649,3.072165,0.134021
Poison,187.088235,169.970588,396.500000,58.764706,67.588235,59.558824,74.029412,69.911765,66.647059,1.970588,0.000000
Normal,750.000000,681.000000,411.500000,63.500000,52.750000,53.750000,88.000000,64.250000,89.250000,6.000000,0.000000

In [176]:
df.groupby(df['Type 1']).mean().sort_values('HP', ascending=False)

,Unnamed: 0,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Dragon,521.843750,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Normal,351.581633,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Fairy,494.529412,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Ground,392.312500,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Water,333.312500,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,465.666667,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Flying,746.500000,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Psychic,420.105263,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Fire,360.942308,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Fighting,400.444444,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Grass,380.414286,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Poison,278.285714,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Dark,507.387097,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Rock,431.840909,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,486.296296,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Ghost,536.281250,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Electric,400.590909,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Bug,368.072464,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000

In [177]:
df.groupby(df['Type 1']).sum()

,Unnamed: 0,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,25397,23080,26146,3925,4897,4880,3717,4471,4256,222,0
Dark,15729,14302,13818,2071,2740,2177,2314,2155,2361,125,2
Dragon,16699,15180,17617,2666,3588,2764,3099,2843,2657,124,12
Electric,17626,15994,19510,2631,3040,2917,3961,3243,3718,144,4
Fairy,8407,7642,7024,1260,1046,1117,1335,1440,826,70,1
Fighting,10812,9824,11244,1886,2613,1780,1434,1747,1784,91,0
Fire,18769,17025,23820,3635,4408,3524,4627,3755,3871,167,5
Flying,2986,2711,1940,283,315,265,377,290,410,22,2
Ghost,17161,15568,14066,2062,2361,2598,2539,2447,2059,134,2
Grass,26629,24141,29480,4709,5125,4956,5425,4930,4335,235,3
Ground,12554,11401,14000,2361,3064,2715,1807,2008,2045,101,4
Ice,11176,10165,10403,1728,1746,1714,1861,1831,1523,85,2
Normal,34455,31279,39365,7573,7200,5865,5470,6245,7012,299,2
Poison,7792,7050,11176,1883,2091,1927,1692,1803,1780,71,0
Psychic,23946,21706,27129,4026,4073,3858,5609,4918,4645,193,14
Rock,19001,17280,19965,2876,4086,4435,2787,3321,2460,152,4
Steel,13130,11957,13168,1761,2503,3412,1823,2177,1492,104,4
Water,37331,33946,48211,8071,8305,8170,8379,7898,7388,320,4

In [178]:
df.groupby(df['Type 1']).count()

,Unnamed: 0,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,,,
Bug,69,69,69,52,69,69,69,69,69,69,69,69,69
Dark,31,31,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,32,32,21,32,32,32,32,32,32,32,32,32
Electric,44,44,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,17,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,27,27,7,27,27,27,27,27,27,27,27,27
Fire,52,52,52,24,52,52,52,52,52,52,52,52,52
Flying,4,4,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,32,32,22,32,32,32,32,32,32,32,32,32
Grass,70,70,70,37,70,70,70,70,70,70,70,70,70
Ground,32,32,32,19,32,32,32,32,32,32,32,32,32
Ice,24,24,24,11,24,24,24,24,24,24,24,24,24
Normal,98,98,98,37,98,98,98,98,98,98,98,98,98
Poison,28,28,28,13,28,28,28,28,28,28,28,28,28
Psychic,57,57,57,19,57,57,57,57,57,57,57,57,57
Rock,44,44,44,35,44,44,44,44,44,44,44,44,44
Steel,27,27,27,22,27,27,27,27,27,27,27,27,27
Water,112,112,112,53,112,112,112,112,112,112,112,112,112

In [179]:
69+31+32+44+17+27+52+4+32+70+32+24+98+28+57+44+27+112

800

In [180]:
df['count']=1

In [181]:
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,count
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1
4,4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1
796,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1
797,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1
798,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1
799,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1

In [184]:
df.groupby(['Type 1','Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64